### ISSUE TITLE
app does not stop with just one ^C, takes two

### ISSUE THREAD

**Issue by prjemian** [prjemian/dhtioc#15]
probably because the DHT is being ready in a thread under continuous loop

**Comment by prjemian** [comment]
after several tries, still takes two (^C^C):

```
[I 13:56:32.863       common: 1079] Connected to new client at 192.168.144.99:43706 (total: 1).
^C[I 13:56:37.745       server:  212] Server task cancelled. Will shut down.
[I 13:56:37.748       server:  222] Server exiting....
^CException ignored in: <module 'threading' from '/usr/lib/python3.7/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 1281, in _shutdown
    t.join()
  File "/usr/lib/python3.7/threading.py", line 1032, in join
    self._wait_for_tstate_lock()
  File "/usr/lib/python3.7/threading.py", line 1048, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
deleting IOC object
stopping DHT sensor
```

**Comment by prjemian** [comment]
Since the app stops from the shell script, this situation is tolerable.
